name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: installing seccomp
      run: sudo apt install libseccomp-dev libseccomp2
    - name: run build
      run: chmod +x build.sh && ./build.sh
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: installing seccomp
      run: sudo apt install libseccomp-dev libseccomp2
    - name: run test
      run: cd build && sudo ./judge.out
